### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by jinlan** [juanosarg/AlphaAnimals#6] opened 2019-04-05 08:14 UTC
My version is : 8c454dd4b966b210780934de233309ac48352f1a

```
Exception ticking world pawn: System.NullReferenceException: Object reference not set to an instance of an object
at Verse.GenGrid.InBounds (Verse.IntVec3,Verse.Map) <0x00015>
at AlphaBehavioursAndEvents.CompGasProducer.CompTick () <0x0021a>
at Verse.ThingWithComps.Tick () <0x0006c>
at (wrapper dynamic-method) Verse.Pawn.Tick_Patch1 (object) <0x00095>
at RimWorld.Planet.WorldPawns.WorldPawnsTick () <0x000e6>

Verse.Log:Error(String, Boolean)
Verse.Log:ErrorOnce(String, Int32, Boolean)
RimWorld.Planet.WorldPawns:WorldPawnsTick()
RimWorld.Planet.World:WorldTick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()

```

**Comment by brucethemoose** [comment] 2019-05-05 19:50
Getting this same error as well.

https://git.io/fjnDq

**Comment by brucethemoose** [comment] 2019-05-05 20:21
Regenerating Avoidgrids with RuntimeGC seemingly fixes the log spam, but destroying all things on the map in dev mode does not.

**Comment by brucethemoose** [comment] 2019-05-06 16:50
The "replace all trade ships" command seemingly fixes the error I was getting, so my issue may be unrelated to this one.

**Comment by juanosarg** [comment] 2020-05-22 07:30
This was caused by the gas comp trying to produce gas on animals travelling on a trader ship. It was fixed by adding a check to see if Map == null

**Closed by juanosarg** 2020-05-22 07:30 UTC
